// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwbiiizsxklozfbzfevq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3YmlpaXpzeGtsb3pmYnpmZXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODI4NjMsImV4cCI6MjA3NDQ1ODg2M30.jbcN0Ant5ut_LZv7o6VKQEEXvDKhsZcKAsXePt7E0DA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});